import React from 'react'

function UserProfilePostsPagePosts() {
    return (
        <div>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
            <h1>Posts</h1>
        </div>
    )
}

export default UserProfilePostsPagePosts
