export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAILURE = "SIGNUP_FAILURE"

export const LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS"

export const GET_FRIEND_REQUEST = "GET_FRIEND_REQUEST"

export const GET_FRIENDS = "GET_FRIENDS"

export const GET_SENT_REQUEST = "GET_SENT_REQUEST"

export const GET_NOTIFICATIONS = "GET_NOTIFICATIONS"