export const ADD_ACTIVE_MESSAGE = "ADD_ACTIVE_MESSAGE"
export const REMOVE_ACTIVE_MESSAGE = "REMOVE_ACTIVE_MESSAGE"
export const ADD_IN_ACTIVE_MESSAGE = "ADD_IN_ACTIVE_MESSAGE"
export const REMOVE_IN_ACTIVE_MESSAGE = "REMOVE_IN_ACTIVE_MESSAGE"
export const ADD_IN_ACTIVE_MESSAGE_TO_ACTIVE_MESSAGE = "ADD_IN_ACTIVE_MESSAGE_TO_ACTIVE_MESSAGE"
export const CLOSE_ALL_MESSAGE ="CLOSE_ALL_MESSAGE"
export const MINIMIZE_ALL_MESSAGE ="MINIMIZE_ALL_MESSAGE"

export const GET_USERS = "GET_USERS"

export const UPDATE_ACTIVE_CONTACTS = "UPDATE_ACTIVE_CONTACTS";

export const GET_CHAT_ROOMS = "GET_CHAT_ROOMS"